alias ga="git add *"
alias gc="git commit -m"
alias gp="git push"
alias scantcp="sudo nmap -p- -T4 -v -A -oA Nmap_Initial $ip"
alias scanudp="sudo nmap -p- -v -sU -sV -T4 -oA Nmap_UDP $ip"
alias webscan="sudo nikto -h http://$ip/ > nikto.txt"
alias gbscan="gobuster dir -u http://$ip/ -v -w /usr/share/dirbuster/wordlists/directory-list-2.3-medium.txt > gbscan.txt"
